# Commands to start on workspace startup
tasks:
  - init: sudo apt update && sudo apt install -y maven
    command: maven install
# Ports to expose on workspace startup
ports:
  - port: 8080
    onOpen: open-preview